apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: audit
  template:
    metadata:
      labels:
        app: audit
    spec:
      containers:
        - name: audit
          image: audit-service:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: audit-config
---
apiVersion: v1
kind: Service
metadata:
  name: audit-service
spec:
  selector:
    app: audit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000